title: HappyCampers.Dance
email: kallin.nagelberg@gmail.com
description: >- 
  The Reality-Adjacent Thoughts of Kallin Nagelberg
url: "http://happycampers.dance"

google_analytics: G-TBRP81DQ3B

github:
  owner_url: https://github.com/Kallin/
  owner_name: Kallin Nagelberg

theme: jekyll-theme-tactile