title: HappyCampers.Dance
email: kallin.nagelberg@gmail.com
description: >- 
  The Reality-Adjacent Thoughts of Kallin Nagelberg
url: "http://happycampers.dance"

github:
  owner_url: https://github.com/Kallin/
  owner_name: Kallin Nagelberg

theme: minima

github: [metadata]

disqus:
  shortname: happycampers-dance

google_analytics: 'G-E6PCF026P8'