version: "3.9"

services:
  jekyll:
    command: jekyll serve --host=0.0.0.0 --force_polling --livereload --drafts
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"

    volumes:
      - .:/usr/src/app